config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    post 'dashboard/:organization/slack_github', to: 'dashboard#slack_github', as: :slack_github

    get 'dashboard/:organization/sync_github', to: 'dashboard#sync_github', as: :sync_github
    get 'dashboard/:organization/sync_slack', to: 'dashboard#sync_slack', as: :sync_slack

    get 'dashboard/:organization', to: 'dashboard#dashboard', as: :organization
    get 'dashboard/:organization/member/:member', to: 'dashboard#member', as: :member
    get 'dashboard/:organization/repo/:repo', to: 'dashboard#repo', as: :repo
  end

end

app/models/app_data.rb
class AppData < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/commit.rb
class Commit < ActiveRecord::Base
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  def full_name
    "#{organization}/#{name}"
  end
end

app/models/slack_github.rb
class SlackGithub < ActiveRecord::Base
end

app/models/slack_message.rb
class SlackMessage < ActiveRecord::Base
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :app_data

  def octokit
    @client ||= Octokit::Client.new(:login => ENV['login'], :password => ENV['password'])
  end

  def app_data
    @app_data ||= (AppData.first || AppData.create(organization: params[:organization]))
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
  def dashboard
    @members = MemberDecorator.decorate_collection(
      Member.where(organization: params[:organization])
    )
    @repos = RepositoryDecorator.decorate_collection(
      Repository.where(organization: params[:organization])
    ).sort_by(&:number_of_commits).reverse!
    @organization = OrganizationDecorator.decorate(
      params[:organization]
    )
    @slack_members = SlackMessage.pluck(:author).uniq
  end

  def member
    @non_pr_commits = CommitDecorator.decorate_collection(
      Commit.where(organization: params[:organization], author: params[:member], pr_number: nil)
      .order('date DESC')
    ).group_by(&:repo)
    @opened_prs = PullRequestDecorator.decorate_collection(
      PullRequest.where(organization: params[:organization], author: params[:member])
      .order('date DESC')
    ).group_by(&:repo)
    @opened_issues = IssueDecorator.decorate_collection(
      Issue.where(organization: params[:organization], author: params[:member])
      .order('date DESC')
    ).group_by(&:repo)
    @comments = CommentDecorator.decorate_collection(
      Comment.where(organization: params[:organization], author: params[:member])
      .order('date DESC')
    ).group_by(&:repo)
  end

  def repo
    @non_pr_commits = CommitDecorator.decorate_collection(
      Commit.where(organization: params[:organization], repo: params[:repo], pr_number: nil)
      .order('date DESC')
    ).group_by(&:author)
    @opened_prs = PullRequestDecorator.decorate_collection(
      PullRequest.where(organization: params[:organization], repo: params[:repo])
      .order('date DESC')
    ).group_by(&:author)
    @opened_issues = IssueDecorator.decorate_collection(
      Issue.where(organization: params[:organization], repo: params[:repo])
      .order('date DESC')
    ).group_by(&:author)
    @comments = CommentDecorator.decorate_collection(
      Comment.where(organization: params[:organization], repo: params[:repo])
      .order('date DESC')
    ).group_by(&:author)
  end

  def sync_github
    GithubSyncService.perform(params[:organization])

    app_data.gh_last_updated = DateTime.current
    app_data.save

    redirect_to admin_organization_path
  end

  def sync_slack
    SlackSyncService.perform(params[:organization], params[:token])

    app_data.slack_last_updated = DateTime.current
    app_data.save

    redirect_to admin_organization_path
  end

  def slack_github
    sg = SlackGithub.find_or_initialize_by(organization: params[:organization], github: params[:github])
    sg.slack = params[:slack]
    sg.save

    render nothing: true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_time_zone

  def set_time_zone
    Time.zone = 'Brasilia'
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/dashboard.html.erb
<h1>Teamtracker for <%= params[:organization] %></h1>

<div class="row">
  <div class="dashboard-members">
    <% @members.each do |member| %>

      <div class="profile-box">
        <div class="avatar">
          <%= image_tag member.avatar_url %>
          <p class="github"><i class="fa fa-github"></i> <%= member.name %></p>
          <p class="slack">
            <i class="fa fa-slack"></i>
            <select name="slack_member" data-github="<%= member.name %>" class="slack_set_member">
              <option value="0" <%= member.slack == "not set" ? "selected" : "" %>>Not Set</option>
              <% @slack_members.each do |sm| %>
                <option value="<%= sm %>" <%= sm == member.slack ? "selected" : "" %>><%= sm %></option>
              <% end %>
            </select>
          </p>
        </div>

        <ul class="statistics">
          <li data-toggle="tooltip" data-placement="left" title="Commits">
            <i class="fa fa-file-code-o"></i> <%= member.number_of_commits %>
          </li>
          <li data-toggle="tooltip" data-placement="left" title="Comments in Issues/PRs">
            <i class="fa fa-comments-o"></i> <%= member.number_of_comments %>
          </li>
          <li data-toggle="tooltip" data-placement="left" title="Messages in slack">
            <i class="fa fa-slack"></i> <%= member.number_of_slack_messages %>
          </li>
          <li>
            <%= link_to admin_member_path(params[:organization], member.name) do %>
              <i class="fa fa-angle-double-right"></i> Details
            <% end %>
          </li>
        </ul>
      </div>

    <% end %>
  </div>

  <div class="dashboard-panel">
    <%= form_tag(admin_sync_github_path, method: :get) do |f| %>
      <div class="input-group">
        <input disabled type="text" class="form-control" placeholder="Last sync at <%= @organization.gh_last_sync %>">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">Sync Github</button>
        </span>
      </div>
    <% end %>

    <%= form_tag(admin_sync_slack_path, method: :get) do |f| %>
      <div class="input-group">
        <input <%= @organization.slack_token.nil? ? "" : "disabled" %> type="text" name="token" class="form-control" placeholder="<%= @organization.slack_token %>">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">&nbsp;&nbsp;Sync Slack</button>
        </span>
      </div>
      <i>Last sync at <%= @organization.slack_last_sync %></i>
    <% end %>

    <h3>General Statistics</h3>
    <ul class="statistics">
      <li>
        <i class="fa fa-file-code-o"></i> <%= @organization.number_of_commits %> Commits
      </li>
      <li>
        <i class="fa fa-comments-o"></i> <%= @organization.number_of_comments %> Comments in Issues/PRs
      </li>
      <li>
        <i class="fa fa-slack"></i> <%= @organization.number_of_slack_messages %> Messages in Slack
      </li>
      <li>
        <i class="fa fa-exclamation-circle"></i> <%= @organization.number_of_issues_open %> Issues open
      </li>
      <li>
        <i class="fa fa-check-circle"></i> <%= @organization.number_of_issues_closed %> Issues closed
      </li>
      <li>

      </li>
    </ul>

    <h3>Repositories</h3>
    <ul class="list-group repositories">
      <% @repos.each do |repo| %>
        <li class="list-group-item">
          <%= link_to repo.name, admin_repo_path(params[:organization], repo.name) %>
          <span class="pull-right"><%= link_to '<i class="fa fa-github"></i> Pulse'.html_safe, "https://github.com/#{params[:organization]}/#{repo.name}/pulse" %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/dashboard/member.html.erb
<h1>Teamtracker for <%= params[:organization] %> / <%= params[:member] %></h1>

<div class="container-fluid">

  <ul class="nav nav-pills tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#commits" aria-controls="profile" role="tab" data-toggle="tab">Commits</a></li>
    <li role="presentation"><a href="#prs" aria-controls="messages" role="tab" data-toggle="tab">Pull Requests</a></li>
    <li role="presentation"><a href="#issues" aria-controls="messages" role="tab" data-toggle="tab">Issues</a></li>
    <li role="presentation"><a href="#activity" aria-controls="messages" role="tab" data-toggle="tab">Activity</a></li>
  </ul>

  <div class="tab-content" id="member-dash">

    <div role="tabpanel" class="tab-pane active" id="home">
      #todo add some cool graphics (maybe d3.js?)
    </div>

    <div role="tabpanel" class="tab-pane" id="commits">
      <h3>Commits</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @non_pr_commits.keys.each do |repo| %>
          <option value="<%= repo %>"><%= repo %></option>
        <% end %>
      </select>

      <% @non_pr_commits.each do |repo, commits| %>
        <ul class="<%= repo.gsub('.', '_') %>">
          <li class="repo_name"><strong><%= repo %></strong></li>
          <% commits.each do |commit| %>
            <li><a href="<%= commit.url %>"><%= commit.sha %></a> <%= commit.message %></a></li>
          <% end %>
          <li><strong>Total commits:</strong> <%= commits.length %></li>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="prs">
      <h3>Pull Requests</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @opened_prs.keys.each do |repo| %>
          <option value="<%= repo %>"><%= repo %></option>
        <% end %>
      </select>

      <% @opened_prs.each do |repo, prs| %>
        <ul class="<%= repo.gsub('.', '_') %>">
          <li class="repo_name"><strong><%= repo %></strong></li>
          <% prs.each do |pull_request| %>
            <li class="<%= pull_request.css_class %>">
              <%= pull_request.merged_badge %> <a href="<%= pull_request.url %>">#<%= pull_request.number %></a> <%= pull_request.title %>
              <a data-toggle="collapse" href="#commits<%= pull_request.number %>" class="collapsor">
                <i class="fa fa-caret-down"></i>
              </a>

              <div class="details collapse" id="commits<%= pull_request.number %>">
                <%= pull_request.body %>
                <ul>
                  <% CommitDecorator.decorate_collection(Commit.where(repo: pull_request.repo, organization: pull_request.organization, pr_number: pull_request.number)).each do |commit| %>
                    <li><a href="<%= commit.url %>"><%= commit.sha %></a> <%= commit.message %></a></li>
                  <% end %>
                </ul>
              </div>
            </li>

          <% end %>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="issues">
      <h3>Issues Opened</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @opened_issues.keys.each do |repo| %>
          <option value="<%= repo %>"><%= repo %></option>
        <% end %>
      </select>

      <% @opened_issues.each do |repo, issues| %>
        <ul class="<%= repo.gsub('.', '_') %>">
          <li class="repo_name"><strong><%= repo %></strong></li>
          <% issues.each do |issue| %>
            <li class="<%= issue.css_class %>"><%= issue.closed_badge %> <a href="<%= issue.url %>">#<%= issue.number %></a> <%= issue.title %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="activity">
      <h3>Issue/PR activity</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @comments.keys.each do |repo| %>
          <option value="<%= repo %>"><%= repo %></option>
        <% end %>
      </select>

      <% @comments.each do |repo, comments| %>
        <ul class="<%= repo.gsub('.', '_') %>">
          <li class="repo_name"><strong><%= repo %></strong></li>
          <% comments.group_by(&:number).each do |number, comments_by_number| %>
            <li>
              <%= comments_by_number.length %> comments on
              <a href="<%= comments_by_number.first.activity_url %>">#<%= number %></a>
            </li>
          <% end %>
          <li><strong>Total comments:</strong> <%= comments.length %></li>
        </ul>
      <% end %>
    </div>

  </div>
</div>

app/views/admin/dashboard/repo.html.erb
<h1>Teamtracker for <%= params[:organization] %> / <%= params[:repo] %></h1>

<div class="container-fluid">

  <ul class="nav nav-pills tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#commits" aria-controls="profile" role="tab" data-toggle="tab">Commits</a></li>
    <li role="presentation"><a href="#prs" aria-controls="messages" role="tab" data-toggle="tab">Pull Requests</a></li>
    <li role="presentation"><a href="#issues" aria-controls="messages" role="tab" data-toggle="tab">Issues</a></li>
    <li role="presentation"><a href="#activity" aria-controls="messages" role="tab" data-toggle="tab">Activity</a></li>
  </ul>

  <div class="tab-content" id="member-dash">

    <div role="tabpanel" class="tab-pane active" id="home">
      #todo add some cool graphics (maybe d3.js?)
    </div>

    <div role="tabpanel" class="tab-pane" id="commits">
      <h3>Commits</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @non_pr_commits.keys.each do |member| %>
          <option value="<%= member %>"><%= member %></option>
        <% end %>
      </select>

      <% @non_pr_commits.each do |member, commits| %>
        <ul class="<%= member.gsub('.', '_') %>">
          <li class="member_name"><strong><%= member %></strong></li>
          <% commits.each do |commit| %>
            <li><a href="<%= commit.url %>"><%= commit.sha %></a> <%= commit.message %></a></li>
          <% end %>
          <li><strong>Total commits:</strong> <%= commits.length %></li>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="prs">
      <h3>Pull Requests</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @opened_prs.keys.each do |member| %>
          <option value="<%= member %>"><%= member %></option>
        <% end %>
      </select>

      <% @opened_prs.each do |member, prs| %>
        <ul class="<%= member.gsub('.', '_') %>">
          <li class="member_name"><strong><%= member %></strong></li>
          <% prs.each do |pull_request| %>
            <li class="<%= pull_request.css_class %>">
              <%= pull_request.merged_badge %> <a href="<%= pull_request.url %>">#<%= pull_request.number %></a> <%= pull_request.title %>
              <a data-toggle="collapse" href="#commits<%= pull_request.number %>" class="collapsor">
                <i class="fa fa-caret-down"></i>
              </a>

              <div class="details collapse" id="commits<%= pull_request.number %>">
                <%= pull_request.body %>
                <ul>
                  <% CommitDecorator.decorate_collection(Commit.where(repo: pull_request.repo, organization: pull_request.organization, pr_number: pull_request.number)).each do |commit| %>
                    <li><a href="<%= commit.url %>"><%= commit.sha %></a> <%= commit.message %></a></li>
                  <% end %>
                </ul>
              </div>
            </li>

          <% end %>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="issues">
      <h3>Issues Opened</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @opened_issues.keys.each do |member| %>
          <option value="<%= member %>"><%= member %></option>
        <% end %>
      </select>

      <% @opened_issues.each do |member, issues| %>
        <ul class="<%= member.gsub('.', '_') %>">
          <li class="member_name"><strong><%= member %></strong></li>
          <% issues.each do |issue| %>
            <li class="<%= issue.css_class %>"><%= issue.closed_badge %> <a href="<%= issue.url %>">#<%= issue.number %></a> <%= issue.title %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="activity">
      <h3>Issue/PR activity</h3>

      <h4>Filter by:</h4>
      <select>
        <option value="all">All</option>
        <% @comments.keys.each do |member| %>
          <option value="<%= member %>"><%= member %></option>
        <% end %>
      </select>

      <% @comments.each do |member, comments| %>
        <ul class="<%= member.gsub('.', '_') %>">
          <li class="member_name"><strong><%= member %></strong></li>
          <% comments.group_by(&:number).each do |number, comments_by_number| %>
            <li>
              <%= comments_by_number.length %> comments on
              <a href="<%= comments_by_number.first.activity_url %>">#<%= number %></a>
            </li>
          <% end %>
          <li><strong>Total comments:</strong> <%= comments.length %></li>
        </ul>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teamtrackerapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>